version: "3.9"
services:

  nginx:
    build:
      context: init/nginx
      dockerfile: Dockerfile
    container_name: nginx-master
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${WEB_DIR}:${PUBLIC_DIR}:rw
      - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d:ro
    networks:
      - lnmp-host

  php:
    build:
      context: init/php
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: php-master
    volumes:
      - ${WEB_DIR}:${PUBLIC_DIR}:rw
    depends_on:
      - nginx
    networks:
      - lnmp-host

  php-sub:
    build:
      context: init/php7
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: php-sub
    volumes:
      - ${WEB_DIR}:${PUBLIC_DIR}:rw
    depends_on:
      - nginx
    networks:
      - lnmp-host

  mysql:
    build:
      context: init/mysql
      dockerfile: Dockerfile
    container_name: mysql-master
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_STORE}:/var/lib/mysql:rw
    command:
      --default-authentication-plugin=${DEFAULT_AUTHENTICATION_PLUGIN}
      --character-set-server=${CHARACTER_SET_SERVER}
      --collation-server=${COLLATION_SERVER}
      --explicit_defaults_for_timestamp=${EXPLICIT_DEFAULTS_FOR_TIMESTAMP}
      --default-storage-engine=${DEFAULT_STORAGE_ENGINE}
      --sql_mode=
    networks:
      - lnmp-host

networks:
  lnmp-host: